### ISSUE TITLE
Remove optima dependency

### ISSUE THREAD

**Issue by mx** [samebchase/hash-set#5]
Optima is listed as a dependency in the asd file, but it doesn't (seem) to appear in the code at all.

**Comment by samebchase** [comment]
@mx Checking.

If you can push a patch without optima in the .asd and all the tests run successfully, I would be happy to accept it.

**Comment by samebchase** [comment]
Yeah, doesn't look like it's used anywhere. Perhaps the code changed, but the dependency wasn't removed.

**Comment by mx** [comment]
Dunno why this didn't close after I submitted my PR. Anyway, manually closing it.
